///
/// @Generated by Mockolo
///



import Foundation
import RealmSwift
@testable import Samidare


class QuestionRepositoryProtocolMock: QuestionRepositoryProtocol {
    init() { }


    static private(set) var getQuestionsCallCount = 0
    static var getQuestionsHandler: ((String) -> ([Question]))?
    static func getQuestions(of group: String) -> [Question] {
        getQuestionsCallCount += 1
        if let getQuestionsHandler = getQuestionsHandler {
            return getQuestionsHandler(group)
        }
        return [Question]()
    }

    static private(set) var addCallCount = 0
    static var addHandler: ((Question) throws -> ())?
    static func add(_ question: Question) throws  {
        addCallCount += 1
        if let addHandler = addHandler {
            try addHandler(question)
        }
        
    }

    static private(set) var updateCallCount = 0
    static var updateHandler: ((Question) throws -> ())?
    static func update(_ question: Question) throws  {
        updateCallCount += 1
        if let updateHandler = updateHandler {
            try updateHandler(question)
        }
        
    }

    static private(set) var deleteCallCount = 0
    static var deleteHandler: ((Question) throws -> ())?
    static func delete(_ question: Question) throws  {
        deleteCallCount += 1
        if let deleteHandler = deleteHandler {
            try deleteHandler(question)
        }
        
    }
}

class AppConfigRepositoryProtocolMock: AppConfigRepositoryProtocol {
    init() { }


    static private(set) var getCallCount = 0
    static var getHandler: (() -> (AppConfig))?
    static func get() -> AppConfig {
        getCallCount += 1
        if let getHandler = getHandler {
            return getHandler()
        }
        fatalError("getHandler returns can't have a default value thus its handler must be set")
    }

    static private(set) var updateCallCount = 0
    static var updateHandler: ((AppConfig) throws -> ())?
    static func update(_ appConfig: AppConfig) throws  {
        updateCallCount += 1
        if let updateHandler = updateHandler {
            try updateHandler(appConfig)
        }
        
    }
}

class QuestionGroupRepositoryProtocolMock: QuestionGroupRepositoryProtocol {
    init() { }


    static private(set) var getCallCount = 0
    static var getHandler: (() -> ([QuestionGroup]))?
    static func get() -> [QuestionGroup] {
        getCallCount += 1
        if let getHandler = getHandler {
            return getHandler()
        }
        return [QuestionGroup]()
    }

    static private(set) var addCallCount = 0
    static var addHandler: ((QuestionGroup) throws -> ())?
    static func add(_ questionGroup: QuestionGroup) throws  {
        addCallCount += 1
        if let addHandler = addHandler {
            try addHandler(questionGroup)
        }
        
    }

    static private(set) var deleteCallCount = 0
    static var deleteHandler: ((QuestionGroup) throws -> ())?
    static func delete(_ questionGroup: QuestionGroup) throws  {
        deleteCallCount += 1
        if let deleteHandler = deleteHandler {
            try deleteHandler(questionGroup)
        }
        
    }
}

