name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode_13.0.app

jobs:
  build:
    runs-on: macOS-latest

    steps:
      # チェックアウト
      - uses: actions/checkout@v2

      # Actionsで使用できるXcodeの一覧出力
      - name: Show Xcode list
        run: ls /Applications | grep 'Xcode'
      
      # 現在使われているXcodeのバージョン出力
      - name: Show Xcode version
        run: xcodebuild -version
      
      # Mintのインストール
      - name: Install Mint
        run: brew install mint
      
      # Mintで管理しているライブラリのキャッシュ
      - name: Cache Mint packages
        uses: actions/cache@v2
        with:
          path: mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-mint-
      
      # プロジェクトファイルの生成
      - name: Generate Xcode project with XcodeGen
        run: mint run xcodegen xcodegen generate
      
      # ビルド
      - name: Xcode build
        run: xcodebuild
          -sdk iphonesimulator
          -configuration Debug
          -scheme Samidare-Develop
          build
      
      # 単体テスト
      - name: Xcode test
        run: xcodebuild
          -sdk iphonesimulator
          -configuration Debug
          -scheme Samidare-Develop
          -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max'
          -skip-testing:Samidare-iOSUITests
          clean test

